apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-java
  labels:
    app: app-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-java
  template:
    metadata:
      labels:
        app: app-java
    spec:
      containers:
        - name: app-java
          image: <aws_account_id>.dkr.ecr.<região>.amazonaws.com/<nome-do-repo>:<tag>
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
